#!/bin/bash

[ -f ~/.config/levelup.conf ] || exit 1;

source ~/.config/levelup.conf

# -- Defaults --
PROJECTS_DIR="$HOME/Projects/"
PROJECT_DIR="${PROJECTS_DIR}${CURRENT_PROJECT_HANDLE}/"

$("$BROWSER" --app="https://www.leveluptutorials.com/tutorials/$CURRENT_TUTORIAL_HANDLE" >> /dev/null)

[ -z "$CURRENT_PROJECT_HANDLE" ] && exit 1;

$TERMINAL -e "vim $PROJECT_DIR"
[ ! -z "$YARN_START" ] && cd $PROJECT_DIR && yarn $YARN_START
