#!/usr/bin/python3

from pyftpdlib.authorizers import DummyAuthorizer
from pyftpdlib.handlers import FTPHandler
from pyftpdlib.servers import FTPServer
from pathlib import Path
import os

home = str(Path.home())
path = home + "/ftp"

isExist = os.path.exists(path)
if not isExist:
   print("`" + path + "` does not exist, creating...")
   os.makedirs(path)

authorizer = DummyAuthorizer()
authorizer.add_user("user", "12345", path, perm="elradfmwMT")

handler = FTPHandler
handler.authorizer = authorizer

server = FTPServer(("127.0.0.1", 1024), handler)
server.serve_forever()
